### ISSUE TITLE
Clarify Contacts Being Removed From the List

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#1956]
## Detailed Description

v1.2.3

Contacts cannot be deleted from the list. Or, potentially, there may need to be a clarification in either docs or the core about removing a contact from the list and actually deleting it. In this pic, you'll see there are two contacts on the grid but none in the list. In my mind, I don't know of a time when you'd want to remove them from the list but not delete them from the grid. If that's the case, removing and deleting/destroying should be the same thing. Otherwise, a simple help line added to remove may be a good option to help FD know they aren't the same?

![Screen Shot 2019-03-17 at 7 24 53 PM](https://user-images.githubusercontent.com/39606064/54501364-7ee51400-48ea-11e9-85b3-e20bfc69315a.png)

**Comment by Justintime50** [comment]
After playing with it, an even simpler approach may be to change the word `Remove` to `Remove from list`.

**Comment by alexanderson1993** [comment]
I'm removing the 'remove' checkbox altogether and just having the delete button showing all the time. Since the contacts in the list are just templates, having them remove from the grid when removed from the list would be unexpected behavior. Same with changing the template contact's images or text label. Once a contact is created, it cannot be changed from the contacts in the list - only by right-clicking on the contact itself.
