### ISSUE TITLE
Single Scan Card (Discussion)

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#1973]
## Detailed Description

Haha putting this in the docs is just asking for trouble. (see pic) 😉 I too was curious why it was broken up into separate systems. I can appreciate the reason for being able to break each system independent of each other. I wonder if there is a better way to incorporate external and internal scans without messing with the flow that current sim centers are used to? I'd love to discuss some options.

![Screen Shot 2019-03-19 at 6 15 26 PM](https://user-images.githubusercontent.com/39606064/54650300-7a983280-4a73-11e9-9853-6e551f18cb07.png)

**Comment by alexanderson1993** [comment]
Sensors scanning was broken into two systems because internal and external are logically separate from one another. They are literally based off of the same class in the code, but perform two separate functions.

It would be possible to practically integrate the two into one. There would just have to be an option to specify which scanner you are using on the scanning card. Behind the scenes, there would still be two systems though.

You are referring to the card, right? Because the core is already integrated into two. If you really did only want to have one, it would be possible to do that as well. You would just have to tell the crew that any scans, internal or external, have to go through the one system, and you would configure it so the other system was hidden.
