### ISSUE TITLE
Request: Don't Allow Warp Engines Until Course Calculated?

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#2006]
## Detailed Description

v1.2.5

I've been in sims and run sims where the crew will blast off to nowhere haha. It actually adds a bit of comedy, but may not be good in the long run? Maybe if Thorium could at least warn the person with engine control that no course is set if warp engines are engaged (if there was no course set) so they can stop and correct it?

**Comment by ZayntIcarus** [comment]
The FD/GM should be paying attention to this and warn them on their end. With sims where maybe they can't set course, or if they're supposed to go off into nowhere, it could just get bothersome.

**Comment by Justintime50** [comment]
Hmm, when would they not be able to set a course or when would they need to go to nowhere?

Is it out of the question then for a notification? I'd agree, lots of things the FD should be keeping their eye on. May help the crew catch their own mistakes though (if it was one aside from the examples you provided.)

**Comment by alexanderson1993** [comment]
This would be tough, because how does Thorium know if the course has been set to the proper place? It only knows if a course has been set, not if it is set to the correct location. That's something the Flight Director has to determine, so this is something Thorium won't be able to handle. This feature is not possible under the current system, so I'm going to close it.
