### ISSUE TITLE
Fix Power Distribution

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#2009]
## Detailed Description

v1.2.5

Power control needs some limits put on it. When you can max out all systems without consequence, it breaks the functionality of the card meaning people can cheat the system and this being one of the more dramatic strategic cards in Thorium, I think they should only be able to divvy out a set amount of power (the amount of power their reactor or batteries supply). This of course would take more careful planning from the FD when configuring sims but would make it much more interesting if they could only assign a certain amount of power so they would have to choose what to sacrifice for what they need at the time.

<img width="874" alt="Screen Shot 2019-03-23 at 10 49 41 PM" src="https://user-images.githubusercontent.com/39606064/54875154-9d518080-4dbe-11e9-88ef-ce7685da83a3.png">

**Comment by alexanderson1993** [comment]
This is one where I'm actually going to leave it as-is. It is the responsibility of the Flight Director to properly address vagrant issues like this when the crew behaves poorly. In this case, they could cause a massive power failure due to the reactor overloading. "Killing" the crew could be a good option as well, to teach the crew that they need to be more careful and just because doing a thing is possible doesn't mean that they should do it. Closing.
