### ISSUE TITLE
Transwarp Doesn't Disable on Insufficient Power

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#2044]
## Detailed Description

v1.2.9

The transwarp card stays active even if 0 power is given to the system.

**Comment by alexanderson1993** [comment]
Since the transwarp's power has to be balanced while the transwarp is activated, it's kind of difficult to automatically know if the power level is at a place where it would be necessary for the transwarp to be deactivated. I'm going to lean more on the side of giving the flight director more control, but also more responsibility, and leave it as-is. Closing.
