### ISSUE TITLE
Navigation Advanced Warp Speed

### ISSUE THREAD

**Issue by sassyspock** [Thorium-Sim/thorium#2266]
**Describe the bug**
When accelerating to warp speeds, the speed is described as null km/s.

**To Reproduce**
1. Use Navigation Advanced card.
2. Activate warp engines at any speed.

**Screenshots**
![image](https://user-images.githubusercontent.com/43680869/58852437-ca8a9c80-8653-11e9-8d36-73d3df70ebeb.png)

**Additional context**
I really like this card, so there will be a few bug reports from me.

**Comment by alexanderson1993** [comment]
This is because the velocity has not been configured in the Warp Engines system on the simulator system config. See screenshot. Closing. 
<img width="660" alt="Screen Shot 2019-06-15 at 3 29 24 PM" src="https://user-images.githubusercontent.com/6558157/59556621-65537700-8f82-11e9-9db1-0763bda6ca91.png">
